// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdlvbxsxbcdydncylnsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbHZieHN4YmNkeWRuY3lsbnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDA5MTMsImV4cCI6MjA2MDQxNjkxM30.ES2bF8W_J2swbkDiDCNa0qXAa58uwzIjdkcHiq-zY2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});